image: docker:stable
services:
  - xeizmendi/docker-dind

variables:
  DOCKER_DRIVER: overlay2
  HTTP_PROXY: "$HTTP_PROXY"
  DOCKER_INSECURE_REGISTRY: "$CI_REGISTRY"
  HTTPS_PROXY: "$HTTP_PROXY"
  NO_PROXY: "$NO_PROXY"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

stages:
  - build
  - deploy

docker-build:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build $DOCKER_BUILD_ARGS -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE
  - docker build $DOCKER_BUILD_ARGS -t $IMAGE_TAG .
  - docker push $IMAGE_TAG  
  only: 
  - /.*homolog/
  - /.*stable/

rancher-deploy-in-homolog:
  stage: deploy
  image: tagip/rancher-cli
  variables:
    RANCHER_URL: $RANCHER_URL
    RANCHER_ACCESS_KEY: $HOMOLOG_KEY
    RANCHER_SECRET_KEY: $HOMOLOG_SECRET
    RANCHER_ENVIRONMENT: HOMOLOG
  script:
    - rancher up --file docker-compose.yml -u -c -s $STACK_NAME --force-upgrade -d
  only: 
  - /.*homolog/

